### ISSUE TITLE
Config Dialogue Text Speed Inverted

### ISSUE THREAD

**Issue by perryliao** [OrangeBetaStar/WaifuBrew#47]
![image](https://user-images.githubusercontent.com/26581943/45666923-f5d05a00-bacb-11e8-9110-4d2c46e22c5c.png)
As picture, dragging the scrollbar to the left makes the text speed faster, and slower if dragged to the right.

**Comment by OrangeBetaStar** [comment]
I didnt know there was convention for these :thonk

**Comment by perryliao** [comment]
Fixed.

Updated `ConfigPane.java` line 107 to the following:
```java
stringTimer.setDelay(100 - slider_speed.getLevel());
```
